### ISSUE TITLE
Read git credentials

### ISSUE THREAD

**Issue by kishaningithub** [thecasualcoder/gg#12]
**Actual Behavior**
When performing a fetch of several repos that require authentication the following happens
```
Failed with error: remote authentication required but no callback set
```

**Expected Behavior**
It should read credentials from wherever git is reading it from. The catch is this is very much platform specific. The location from where git reads the creds can be found out by running

```bash
$ git config credential.helper
```

For example, in macosx this points to osxkeychain

**Comment by jpninanjohn** [comment]
@jskswamy also mentioned this. Will look into it

**Comment by jpninanjohn** [comment]
Actually currently it only uses this to authenticate. `~/.ssh/id_rsa`. If this is cannot be used for a repo it will fail.

**Comment by jpninanjohn** [comment]
Hi @kishaningithub. This should work now. See the ggConf example file to configure the ssh.

Closing this now. Please reopen if any issues occur.

**Comment by jpninanjohn** [comment]
@jskswamy Can you also check if this works for you now?

**Comment by jskswamy** [comment]
@jpninanjohn it works without any issue, thanks for the fix
