### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by not-matthias** [thecasualcoder/gg#25]
As already in the title mentioned, are you planning on supporting Windows too? The only thing that should differ, is the extraction of the git credentials as mentioned here: #12, right?

**Comment by jpninanjohn** [comment]
Yes, we want this to work on all platforms.
I am not sure about the difference though. If thats the only difference then yes, it should solve the issue.

**Comment by jpninanjohn** [comment]
The git creds can be configured via the config file now. As mentioned if this is the only change required then it should work on windows. Can you please check?

**Comment by not-matthias** [comment]
Unfortunately Windows has a different name for the `HOME` environment variable. It's equivalent to `%userprofile%` or `%homepath%`.  If you manually add the `HOME` environment variable, everything works fine.

**Comment by jpninanjohn** [comment]
Try configuring it via the ggconf file. Look at `ggconf.example.yaml`

**Comment by f0ff886f** [comment]
I tried compiling on Windows and I get an error, I'm a rust newbie so no idea if this is a project thing or just a "my machine" thing:

```
gg on  master is 📦 v0.3.2 via 🐍 v3.7.6 (.venv) via 🦀 v1.42.0 took 10s
❯ cargo install --path .
  Installing git-governance v0.3.2 (C:\Work\GitHub\gg)
    Updating crates.io index
error: failed to compile `git-governance v0.3.2 (C:\Work\GitHub\gg)`, intermediate artifacts can be found at `C:\Work\GitHub\gg\target`

Caused by:
  failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)
--- stdout
___.exe
lib___.rlib
___.dll
___.dll
___.lib
___.dll
C:\Users\Matt\scoop\apps\rust-msvc\1.42.0
debug_assertions
proc_macro
target_arch="x86_64"
target_endian="little"
target_env="msvc"
target_family="windows"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_os="windows"
target_pointer_width="64"
target_vendor="pc"
windows
```

Otherwise I'd be happy to try and get the configuration test verified.

**Comment by jpninanjohn** [comment]
@f0ff886f 
Looks there has to be more work to be done for windows. I unfortunately dont have a windows machine setup to try now. 

Can you try re-installing rust via rustup(if you have't done it via `rustup`) and check?

**Comment by f0ff886f** [comment]
Hm, I now installed via `rustup` (I am using `rustup-msvc` from `scoop`). It has worked perfectly right now! I'm using it for the `gg status` command.

**Comment by jpninanjohn** [comment]
Cool. Closing this issue then.
