### ISSUE TITLE
Make gg work with multithreading/parallelism

### ISSUE THREAD

**Issue by jpninanjohn** [thecasualcoder/gg#27]
@tinou98 has started work on this already. PR -> #26

**Comment by jpninanjohn** [comment]
#26 is merged. There are still some changes pending. @tinou98 Once you are done create another PR and link it to this issue. 

Pending:
https://github.com/thecasualcoder/gg/pull/26#discussion_r394174925
https://github.com/thecasualcoder/gg/pull/26#issuecomment-600092818

**Comment by jpninanjohn** [comment]
@tinou98 are you still working on this?

**Comment by tinou98** [comment]
I've finished implementing everything I was thinking of. If there are others stuff to implement, maybe we can create others issues, and close this one ?

**Comment by jpninanjohn** [comment]
Cool. Closing this then
