### ISSUE TITLE
Add a global config file

### ISSUE THREAD

**Issue by dineshba** [thecasualcoder/gg#4]
- It can have paths to ignore.

Feature request from @jskswamy

**Comment by aswinkarthik** [comment]
Would love to contribute to this.

**Comment by jpninanjohn** [comment]
Yes please....

**Comment by jpninanjohn** [comment]
@jskswamy This is done. Its not deployed in brew yet. Can you build and check pls?

**Comment by jpninanjohn** [comment]
Updated readme on this too

**Comment by jpninanjohn** [comment]
Closing this
